### ISSUE TITLE
File reading fails

### ISSUE THREAD

**Issue by JaniKallankari** [maxpat78/FATtools2#1]
Hi,

I'm having problems reading files. I see files with list command but when I try to read I get following error:

>  Traceback
>  (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "FAT.py", line 968, in read
>     self.update_time()
>   File "FAT.py", line 953, in update_time
>     self.Entry.wADate = cdate
> AttributeError: 'NoneType' object has no attribute 'wADate'
> 

Could you provide example how files can be read? I'm using raspbian strech (linux).
Thanks, 
  Jani

**Comment by maxpat78** [comment]
Read interface works in a way similar to Python's built-in file object, a good sample is in test/stress.py.

What OS/file-system driver did generate your test FAT file system? I think the problem could be your system does not set last access date field in the slot entry. Could you provide to me a little sample FAT image to investigate the problem?

**Comment by maxpat78** [comment]
And, however, could you provide me a sample python code to look at the way you are trying to read the file?
