### ISSUE TITLE
What license is your code under?

### ISSUE THREAD

**Issue by Cu3PO42** [maxpat78/FATtools2#3]
Hi there!

This looks like a great project and it is just what I need for a new tool I'm working on. So thank you so much for making this! Since you shared this on GitHub, I'm assuming you meant for it to be used by other people. However, you did not specify a license, or at least I can't seem to find one.

Not having a license means that no-one is allowed to modify your code or use it in any project of theirs (and thereby share it again), which is a shame!

[choosealicense.com](https://choosealicense.com/) is a great overview of available licenses and what choosing them entails for your project. I hope you can find one that matches your idea of what should happen with this code.

Thank you for taking the time to look at this!

Best regards,
Cu3PO42

**Comment by maxpat78** [comment]
> 
> 
> Hi there!
> 
> This looks like a great project and it is just what I need for a new tool I'm working on. So thank you so much for making this! Since you shared this on GitHub, I'm assuming you meant for it to be used by other people. However, you did not specify a license, or at least I can't seem to find one.
> 
> Not having a license means that no-one is allowed to modify your code or use it in any project of theirs (and thereby share it again), which is a shame!
> 
> [choosealicense.com](https://choosealicense.com/) is a great overview of available licenses and what choosing them entails for your project. I hope you can find one that matches your idea of what should happen with this code.
> 
> Thank you for taking the time to look at this!
> 
> Best regards,
> Cu3PO42

Now it is GPLed. Please prefer FATtools3, the Python3 revision.

**Comment by Cu3PO42** [comment]
Thanks so much! And thank you for making me aware of the existence of FATTools3, I was going to port this one myself...
