### ISSUE TITLE
Accidental global in disk.py

### ISSUE THREAD

**Issue by the-moog** [maxpat78/FATtools2#5]
buf is referenced in win32_disk:read() but it does not exist in the function.
Is this a global or an error?
the target of buf, s is then never used locally.

**Comment by maxpat78** [comment]
I'll fix it. In fact I've fixed such bug long ago, as you can see in the Python3 codebase (FATtools3 repo). Perhaps I forgot to update 2.x code!

**Comment by the-moog** [comment]
I suggest putting a link in the GitHub front page for the Py2 version, pointing to the Py3 port.
